"""Representative metro line colors used by the frontend map.

The raw metro CSVs do not include line colors, so this module assigns a
stable display color from each city's published/common route colors.  The
function accepts the normalized line names generated by preprocess_raw.py.
"""

from __future__ import annotations

import re


DEFAULT_LINE_COLOR = "#8b9aaa"


NUMERIC_LINE_COLORS: dict[str, dict[str, str]] = {
    # Beijing Subway / Beijing MTR route colors.
    "110000": {
        "1": "#A4343A",
        "2": "#006098",
        "3": "#E35205",
        "4": "#008E9B",
        "5": "#A05EB5",
        "6": "#D4A900",
        "7": "#F6C95B",
        "8": "#009B77",
        "9": "#8FC31F",
        "10": "#009DDC",
        "11": "#8A1538",
        "12": "#B7BF10",
        "13": "#F9E300",
        "14": "#CA4F7C",
        "15": "#653279",
        "16": "#76B900",
        "17": "#00A3E0",
        "19": "#D0006F",
        "22": "#F15A24",
        "28": "#00A3AD",
    },
    # Shanghai Metro route colors.
    "310000": {
        "1": "#E4002B",
        "2": "#8CC63F",
        "3": "#FFD100",
        "4": "#6F2DA8",
        "5": "#A05EB5",
        "6": "#D0006F",
        "7": "#F58220",
        "8": "#0072CE",
        "9": "#77C5D5",
        "10": "#C1A7E2",
        "11": "#7A3E2F",
        "12": "#007A3D",
        "13": "#F2A7C7",
        "14": "#A6A300",
        "15": "#C8A165",
        "16": "#00B5E2",
        "17": "#B77729",
        "18": "#B48A5A",
        "19": "#8A6F4D",
        "20": "#00AEEF",
        "21": "#9BCB3C",
        "22": "#E87722",
        "23": "#8E44AD",
    },
    # Guangzhou Metro route colors.
    "440100": {
        "1": "#F3D03E",
        "2": "#006EB6",
        "3": "#F58220",
        "4": "#00A650",
        "5": "#C8102E",
        "6": "#80225F",
        "7": "#97D700",
        "8": "#00A3AD",
        "9": "#71C5E8",
        "10": "#6E6259",
        "11": "#7A003C",
        "12": "#00B0B9",
        "13": "#8D6E1F",
        "14": "#81312F",
        "18": "#005EB8",
        "21": "#5B2C83",
        "22": "#F2C75C",
    },
    # Chengdu Metro route colors.
    "510100": {
        "1": "#0072BC",
        "2": "#F28C28",
        "3": "#D21872",
        "4": "#00A651",
        "5": "#6F2DA8",
        "6": "#8B5E3C",
        "7": "#5BC2E7",
        "8": "#9ACD32",
        "9": "#F6A800",
        "10": "#00A3E0",
        "13": "#B31B1B",
        "17": "#7AC143",
        "18": "#00B2A9",
        "19": "#B565A7",
        "27": "#87C540",
        "30": "#00A6A6",
    },
    # Hangzhou Metro route colors.
    "330100": {
        "1": "#E4002B",
        "2": "#F28C28",
        "3": "#FFD100",
        "4": "#00A651",
        "5": "#00A3E0",
        "6": "#0072CE",
        "7": "#7B2CBF",
        "8": "#D0006F",
        "9": "#8B5A2B",
        "10": "#C5B358",
        "12": "#00A3AD",
        "15": "#B56576",
        "16": "#F58220",
        "18": "#6F2DA8",
        "19": "#00B5E2",
    },
    # Shenzhen Metro route colors.
    "440300": {
        "1": "#00A65A",
        "2": "#F58220",
        "3": "#00A3E0",
        "4": "#C8102E",
        "5": "#7B2CBF",
        "6": "#00AFAA",
        "7": "#003DA5",
        "8": "#F58220",
        "9": "#7A7A7A",
        "10": "#E4007F",
        "11": "#4B2E83",
        "12": "#8E44AD",
        "13": "#F6A800",
        "14": "#FFD100",
        "15": "#B565A7",
        "16": "#005EB8",
        "17": "#00A651",
        "19": "#C5B358",
        "20": "#00B5E2",
        "22": "#8B5E3C",
        "25": "#7AC143",
        "27": "#6F2DA8",
        "29": "#E87722",
        "32": "#71C5E8",
    },
}


SPECIAL_LINE_COLORS: dict[str, list[tuple[str, str]]] = {
    "110000": [
        ("13A", "#F9E300"),
        ("13B", "#F9E300"),
        ("昌平", "#DE7C9B"),
        ("房山", "#E87722"),
        ("燕房", "#E87722"),
        ("亦庄", "#C6007E"),
        ("首都机场", "#A05EB5"),
        ("大兴国际机场", "#006C8F"),
        ("西郊", "#C8102E"),
    ],
    "310000": [
        ("浦江", "#B5BD00"),
        ("嘉闵", "#E87722"),
        ("南汇", "#00A3E0"),
        ("示范区", "#00A651"),
        ("南枫", "#A05EB5"),
        ("机场线", "#00A3AD"),
    ],
    "440100": [
        ("APM", "#00B5E2"),
        ("广佛", "#7AC143"),
    ],
    "510100": [
        ("S3", "#00A3E0"),
        ("S5", "#7B2CBF"),
        ("S11", "#00A651"),
        ("蓉2", "#C8102E"),
    ],
    "330100": [
        ("杭海", "#00A3E0"),
        ("杭德", "#7AC143"),
    ],
    "440300": [
        ("云巴", "#7AC143"),
        ("坪山云巴", "#7AC143"),
    ],
}


def _line_number(line_name: str) -> str | None:
    match = re.search(r"(\d+)\s*号线", line_name)
    if match:
        return match.group(1)
    return None


def get_line_color(line_name: str, city_code: str) -> str:
    """Return a representative route color for a line name."""
    if not line_name:
        return DEFAULT_LINE_COLOR

    for keyword, color in SPECIAL_LINE_COLORS.get(city_code, []):
        if keyword in line_name:
            return color

    line_no = _line_number(line_name)
    if line_no:
        return NUMERIC_LINE_COLORS.get(city_code, {}).get(line_no, DEFAULT_LINE_COLOR)

    return DEFAULT_LINE_COLOR
